pipeline:
  build:
    image: elixir:1.6
    commands:
      - env
      - mix do local.rebar --force, local.hex --force, deps.get
      - MIX_ENV=dev mix do format --check-formatted, credo --all
      - MIX_ENV=test mix coveralls.json
